backend:
  name: git-gateway
  branch: master

local_backend:
  url: http://localhost:8076/api/v1

media_folder: "media"
public_folder: "/media"

collections:
  - label: "Events"
    name: "events"
    folder: "_events"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    create: true
    editor:
      preview: false
    fields:
      - label: "Event Start Time"
        name: "start"
        widget: "datetime"
        default: ""
        dateFormat: "DD.MM.YYYY" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "LLL"
        pickerUtc: false
      - label: "Event End Time"
        name: "end"
        widget: "datetime"
        default: ""
        dateFormat: "DD.MM.YYYY" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "LLL"
        pickerUtc: false
      - { label: "Title (English)", name: "title", widget: "string" }
      - { label: "Body (English)", name: "body", widget: "markdown" }
      - { label: "Title (Spanish)", name: "title-es", widget: "string" }
      - { label: "Body (Spanish)", name: "body-es", widget: "markdown" }
  - label: "Staff Members"
    name: "our-staff"
    folder: "_our-staff"
    slug: "{{name}}"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Name",
          name: "name",
          widget: "string",
          default: "",
        }
      - { label: "About You (Snglish)", name: "body", widget: "markdown" }
      - { label: "About You (Spanish)", name: "body", widget: "markdown" }
